export const language = {
  english: {
    header: {
      link1: "Home",
      link2: "Projects",
      connect: "Connect Wallet",
    },
    footer: {
      copyright: "Copyright © 2023 Ordinal Pad. All Rights Reserves",
      link1: "Docs",
      link2: "Blogs",
      link3: "Terms & Conditions",
      link4: "Privacy Policy",
    },
    landing: {
      hero: {
        btn1: "Launchpad",
        title: "Get early access to the best projects within the",
        titleGr: "Ordinal Ecosystem",
        sub: "Vetted projects that will drive the future the of ",
        subGr: "Bitcoin Ordinal Ecosystem",
        btn2: "Submit Project",
        btn3: "Join Presales",
        value1: "Projects Funded",
        value2: "Projects MKT cap",
        value3: "Unique participants",
        cardText: {
          imgText: "Featured Project",
          date: "Starting",
          desc: "The Ultimate Launchpad Created Exclusively For The Bitcoin Ordinal Ecosystem.",
          btn1: "Token Sale",
          btn2: "Buy Here",
          price: "Price per Token",
          allocation: "Allocation",
        },
      },
      funds: {
        title: "Raised Funds to Build within the  ",
        titleGr: "Ordinal",
        titleEnd: "Ecosystem",
        box1: "Total Raised",
        box2: "Tokens Funded",
        box3: "Total MKT Cap",
        box4: "Total Participants",
      },
      how: {
        title: "How to Buy Ordinal Pad $OPAD token?",
        btn: "Buy $OPAD",
      },
      upcoming: {
        title: "Upcoming Projects",
        sub: "We bring in some of the most vetted and successful projects within the Ordinal Ecosystem",
        days: "Days",
        hours: "Hours",
        min: "Minutes",
        sec: "Seconds",
        date: "Starting",
        price: "Price per Token",
        allocation: "Allocation",
        note: "Providing a platform to assist with the most innovative ordinal projects",
        btnCard: "Token Sale",
        btn1: "See All",
      },
      brand: {
        btn1: "Launchpad",
        title: "Brand Ambassadors",
        btn2: "See All",
        followers: "Followers",
      },
      launched: {
        title: "Launched",
        titleGr: "Projects",
        raised: "Total Raised",
        participants: "Participants",
        ended: "Ended",
      },
      sale: {
        title: "Never want to miss a sale?",
        btn: "Join Our Community",
      },
    },
  },
  german: {
    header: {
      link1: "Heim",
      link2: "Projekte",
      connect: "Brieftasche verbinden",
    },
    footer: {
      copyright: "Copyright © 2023 Ordinalblock. Alle Rechte vorbehalten",
      link1: "Dokumente",
      link2: "Blogs",
      link3: "Terms & Bedingungen",
      link4: "Datenschutz-Bestimmungen",
    },
    landing: {
      hero: {
        btn1: "Startrampe",
        title:
          "Erhalten Sie frühzeitig Zugriff auf die besten Projekte innerhalb der",
        titleGr: "Ordinales Ökosystem",
        sub: "Geprüfte Projekte, die die Zukunft vorantreiben werden",
        subGr: "Bitcoin-Ordinal-Ökosystem",
        btn2: "Projekt einreichen",
        btn3: "Nehmen Sie am Vorverkauf teil",
        value1: "Geförderte Projekte",
        value2: "Projekte MKT-Kappe",
        value3: "Einzigartige Teilnehmer",
        cardText: {
          imgText: "Vorgestelltes Projekt",
          date: "Beginnend",
          desc: "Das ultimative Launchpad, das exklusiv für das Bitcoin-Ordinal-Ökosystem entwickelt wurde.",
          btn1: "Token-Verkauf",
          btn2: "Kaufen Sie hier",
          price: "Preis pro Token",
          allocation: "Zuweisung",
        },
      },
      funds: {
        title: "Aufgebrachte Mittel zum Bauen innerhalb der",
        titleGr: "Ordinal",
        titleEnd: "Ökosystem",
        box1: "Insgesamt angehoben",
        box2: "Token finanziert",
        box3: "Gesamt MARKT Kap",
        box4: "Teilnehmer insgesamt",
      },
      how: {
        title: "Wie kaufe ich Ordinal Pad $OPAD-Token?",
        btn: "$OPAD kaufen",
      },
      upcoming: {
        title: "Bevorstehende Projekte",
        sub: "Wir bringen einige der am besten geprüften und erfolgreichsten Projekte innerhalb des Ordinal-Ökosystems ein",
        days: "Tage",
        hours: "Std",
        min: "Protokoll",
        sec: "Sekunden",
        date: "Beginnend",
        price: "Preis pro Token",
        allocation: "Zuweisung",
        note: "Bereitstellung einer Plattform zur Unterstützung der innovativsten ordinalen Projekte",
        btnCard: "Token-Verkauf",
        btn1: "Alles sehen",
      },
      brand: {
        btn1: "Startrampe",
        title: "Markenbotschafter",
        btn2: "Alles sehen",
        followers: "Anhänger",
      },
      launched: {
        title: "Gestartet",
        titleGr: "Projekte",
        raised: "Insgesamt angehoben",
        participants: "Teilnehmer",
        ended: "Beendet",
      },
      sale: {
        title: "Du willst keinen Sale verpassen?",
        btn: "tritt unserer Gemeinschaft bei",
      },
    },
  },
};
