export const language = {
  english: {
    header: {
      link1: "Home",
      link2: "Projects",
      connect: "Connect Wallet",
    },
    footer: {
      copyright: "Copyright © 2023 Ordinal Pad. All Rights Reserves",
      link1: "Docs",
      link2: "Blogs",
      link3: "Terms & Conditions",
      link4: "Privacy Policy",
    },
    landing: {
      hero: {
        btn1: "Launchpad",
        title: "Get early access to the best projects within the",
        titleGr: "Ordinal Ecosystem",
        sub: "Vetted projects that will drive the future the of ",
        subGr: "Bitcoin Ordinal Ecosystem",
        btn2: "Submit Project",
        btn3: "Join Presales",
        value1: "Projects Funded",
        value2: "Projects MKT cap",
        value3: "Unique participants",
        cardText: {
          imgText: "Featured Project",
          date: "Starting",
          desc: "The Ultimate Launchpad Created Exclusively For The Bitcoin Ordinal Ecosystem.",
          btn1: "Token Sale",
          btn2: "Buy Here",
          price: "Price per Token",
          allocation: "Allocation",
        },
      },
      funds: {
        title: "Raised Funds to Build within the  ",
        titleGr: "Ordinal",
        titleEnd: "Ecosystem",
        box1: "Total Raised",
        box2: "Tokens Funded",
        box3: "Total MKT Cap",
        box4: "Total Participants",
      },
      how: {
        title: "How to Buy Ordinal Pad $OPAD token?",
        btn: "Buy $OPAD",
      },
      upcoming: {
        title: "Upcoming Projects",
        sub: "We bring in some of the most vetted and successful projects within the Ordinal Ecosystem",
        days: "Days",
        hours: "Hours",
        min: "Minutes",
        sec: "Seconds",
        date: "Starting",
        price: "Price per Token",
        allocation: "Allocation",
        note: "Providing a platform to assist with the most innovative ordinal projects",
        btnCard: "Token Sale",
        btn1: "See All",
      },
      brand: {
        btn1: "Launchpad",
        title: "Brand Ambassadors",
        btn2: "See All",
        followers: "Followers",
      },
      launched: {
        title: "Launched",
        titleGr: "Projects",
        raised: "Total Raised",
        participants: "Participants",
        ended: "Ended",
      },
      sale: {
        title: "Never want to miss a sale?",
        btn: "Join Our Community",
      },
    },
    projectDetails: {
      hero: {
        title: "Project Details",
        desc: "The Ultimate Launchpad Designed Exclusively For The Ordinal Ecosystem",
        owner: "Owner",
        chain: "Blockchain",
        address: "Contract Address",
        id: "Token ID",
        standard: "Token Standard",
        fees: "Contract Fees",
        time: "Launch Time",
        btn1: "Chart",
        btn2: "Buy Now",
      },
      desc: {
        tab1: "Description",
        tab2: "Token Sale",
        titleGr: "Oridnal Pad",
        title:
          "is the perfect launchpad for the Ordinal ecosystem for several reasons:",
        para1:
          "- Firstly, it is an user-friendly and secure platform that allows users to easily participate in Ordinal's most promising projects before they launch. Because of our platform's simple and intuitive design, even those who are new to cryptocurrency and DeFi can easily navigate the platform and start participating in projects without any technical knowledge.",
        para2:
          "- Secondly, Ordinal Pad has integrated various features that make it easy for users to stake their tokens in order to earn a generous yield, while they are waiting for new project launches.. Additionally, we are building a strong community of users and developers who are constantly working to improve the platform, adding new features and optimizing existing ones.",
        para3:
          "Overall, Ordinal Pad's accessibility, user-friendly interface, and robust features set make it the perfect launchpad for the Ordinal ecosystem.",
        btn1: "Whitepaper",
        tags: "Tags",
        social: "Socials",
      },
    },
  },
  german: {
    header: {
      link1: "Heim",
      link2: "Projekte",
      connect: "Brieftasche verbinden",
    },
    footer: {
      copyright: "Copyright © 2023 Ordinalblock. Alle Rechte vorbehalten",
      link1: "Dokumente",
      link2: "Blogs",
      link3: "Terms & Bedingungen",
      link4: "Datenschutz-Bestimmungen",
    },
    landing: {
      hero: {
        btn1: "Startrampe",
        title:
          "Erhalten Sie frühzeitig Zugriff auf die besten Projekte innerhalb der",
        titleGr: "Ordinales Ökosystem",
        sub: "Geprüfte Projekte, die die Zukunft vorantreiben werden",
        subGr: "Bitcoin-Ordinal-Ökosystem",
        btn2: "Projekt einreichen",
        btn3: "Nehmen Sie am Vorverkauf teil",
        value1: "Geförderte Projekte",
        value2: "Projekte MKT-Kappe",
        value3: "Einzigartige Teilnehmer",
        cardText: {
          imgText: "Vorgestelltes Projekt",
          date: "Beginnend",
          desc: "Das ultimative Launchpad, das exklusiv für das Bitcoin-Ordinal-Ökosystem entwickelt wurde.",
          btn1: "Token-Verkauf",
          btn2: "Kaufen Sie hier",
          price: "Preis pro Token",
          allocation: "Zuweisung",
        },
      },
      funds: {
        title: "Aufgebrachte Mittel zum Bauen innerhalb der",
        titleGr: "Ordinal",
        titleEnd: "Ökosystem",
        box1: "Insgesamt angehoben",
        box2: "Token finanziert",
        box3: "Gesamt MARKT Kap",
        box4: "Teilnehmer insgesamt",
      },
      how: {
        title: "Wie kaufe ich Ordinal Pad $OPAD-Token?",
        btn: "$OPAD kaufen",
      },
      upcoming: {
        title: "Bevorstehende Projekte",
        sub: "Wir bringen einige der am besten geprüften und erfolgreichsten Projekte innerhalb des Ordinal-Ökosystems ein",
        days: "Tage",
        hours: "Std",
        min: "Protokoll",
        sec: "Sekunden",
        date: "Beginnend",
        price: "Preis pro Token",
        allocation: "Zuweisung",
        note: "Bereitstellung einer Plattform zur Unterstützung der innovativsten ordinalen Projekte",
        btnCard: "Token-Verkauf",
        btn1: "Alles sehen",
      },
      brand: {
        btn1: "Startrampe",
        title: "Markenbotschafter",
        btn2: "Alles sehen",
        followers: "Anhänger",
      },
      launched: {
        title: "Gestartet",
        titleGr: "Projekte",
        raised: "Insgesamt angehoben",
        participants: "Teilnehmer",
        ended: "Beendet",
      },
      sale: {
        title: "Du willst keinen Sale verpassen?",
        btn: "tritt unserer Gemeinschaft bei",
      },
    },
    projectDetails: {
      hero: {
        title: "Projekt Details",
        desc: "Das ultimative Launchpad, das exklusiv für das Ordinal-Ökosystem entwickelt wurde",
        owner: "Eigentümer",
        chain: "Blockchain",
        address: "Vertragsadresse",
        id: "Token-ID",
        standard: "Token-Standard",
        fees: "Vertragsgebühren",
        time: "Startzeit",
        btn1: "Diagramm",
        btn2: "Kaufe jetzt",
      },
      desc: {
        tab1: "Beschreibung",
        tab2: "Token-Verkauf",
        titleGr: "Oridnal Pad",
        title:
          "ist aus mehreren Gründen die perfekte Startrampe für das Ordinal-Ökosystem:",
        para1:
          "- Erstens ist es eine benutzerfreundliche und sichere Plattform, die es Benutzern ermöglicht, sich leicht an den vielversprechendsten Projekten von Ordinal zu beteiligen, bevor sie gestartet werden. Aufgrund des einfachen und intuitiven Designs unserer Plattform können selbst diejenigen, die neu in Kryptowährung und DeFi sind, leicht auf der Plattform navigieren und ohne technische Kenntnisse an Projekten teilnehmen.",
        para2:
          "- Zweitens hat Ordinal Pad verschiedene Funktionen integriert, die es Benutzern erleichtern, ihre Token zu staken, um einen großzügigen Ertrag zu erzielen, während sie auf den Start neuer Projekte warten. Darüber hinaus bauen wir eine starke Community von Benutzern und Entwicklern auf, die arbeiten ständig daran, die Plattform zu verbessern, neue Funktionen hinzuzufügen und bestehende zu optimieren.",
        para3:
          "Insgesamt machen die Zugänglichkeit, die benutzerfreundliche Oberfläche und die robusten Funktionen von Ordinal Pad das perfekte Startfeld für das Ordinal-Ökosystem.",
        btn1: "Weißes Papier",
        tags: "Stichworte",
        social: "Soziales",
      },
    },
  },
};
