export const language = {
  english: {
    header: {
      link1: "Home",
      link2: "Projects",
      connect: "Connect Wallet",
    },
    footer: {
      copyright: "Copyright © 2023 Ordinal Pad. All Rights Reserves",
      link1: "Docs",
      link2: "Blog",
      link3: "Terms & Conditions",
      link4: "Privacy Policy",
    },
    landing: {
      hero: {
        btn1: "Launchpad",
        title: "Get early access to the best projects within the",
        titleGr: "Ordinal Ecosystem",
        sub: "Vetted projects that will drive the future the of ",
        subGr: "Bitcoin Ordinal Ecosystem",
        btn2: "Submit Project",
        btn3: "Join Presales",
        value1: "Projects Funded",
        value2: "Projects MKT cap",
        value3: "Unique participants",
        cardText: {
          imgText: "Featured Project",
          date: "Starting",
          desc: "The Ultimate Launchpad Created Exclusively For The Bitcoin Ordinal Ecosystem.",
          btn1: "Token Sale",
          btn2: "Buy Here",
          price: "Price per Token",
          allocation: "Allocation",
        },
      },
      funds: {
        title: "Funds Raised to Build within the  ",
        titleGr: "Ordinal",
        titleEnd: "Ecosystem",
        box1: "Total Raised",
        box2: "Tokens Funded",
        box3: "Total MKT Cap",
        box4: "Total Participants",
      },
      how: {
        title: "How to Buy Ordinal Pad $OPAD token?",
        btn: "Buy $OPAD",
      },
      upcoming: {
        title: "Upcoming Projects",
        sub: "We bring in some of the most vetted and successful projects within the Ordinal Ecosystem",
        days: "Days",
        hours: "Hours",
        min: "Minutes",
        sec: "Seconds",
        date: "Starting",
        price: "Price per Token",
        allocation: "Allocation",
        note: "Providing a platform to assist with the most innovative ordinal projects",
        btnCard: "Token Sale",
        btn1: "See All",
      },
      brand: {
        btn1: "Launchpad",
        title: "Brand Ambassadors",
        btn2: "See All",
        followers: "Followers",
      },
      launched: {
        title: "Launched",
        titleGr: "Projects",
        raised: "Total Raised",
        participants: "Participants",
        ended: "Ended",
      },
      sale: {
        title: "Never want to miss a sale?",
        btn: "Join Our Community",
      },
    },
    projectDetails: {
      hero: {
        title: "Project Details",
        desc: "The Ultimate Launchpad Designed Exclusively For The Ordinal Ecosystem",
        owner: "Owner",
        chain: "Blockchain",
        address: "Contract Address",
        id: "Token ID",
        standard: "Token Standard",
        fees: "Contract Fees",
        time: "Launch Time",
        btn1: "Chart",
        btn2: "Buy Now",
      },
      desc: {
        tab1: "Description",
        tab2: "Token Sale",
        titleGr: "Oridnal Pad",
        title:
          "is the perfect launchpad for the Ordinal ecosystem for several reasons:",
        para1:
          "- Firstly, it is an user-friendly and secure platform that allows users to easily participate in Ordinal's most promising projects before they launch. Because of our platform's simple and intuitive design, even those who are new to cryptocurrency and DeFi can easily navigate the platform and start participating in projects without any technical knowledge.",
        para2:
          "- Secondly, Ordinal Pad has integrated various features that make it easy for users to stake their tokens in order to earn a generous yield, while they are waiting for new project launches.. Additionally, we are building a strong community of users and developers who are constantly working to improve the platform, adding new features and optimizing existing ones.",
        para3:
          "Overall, Ordinal Pad's accessibility, user-friendly interface, and robust features set make it the perfect launchpad for the Ordinal ecosystem.",
        btn1: "Whitepaper",
        tags: "Tags",
        social: "Socials",
      },
    },
  },
  chinese: {
    header: {
      link1: "家",
      link2: "项目",
      connect: "连接钱包",
    },
    footer: {
      copyright: "版权所有 © 2023 序号块。版权所有",
      link1: "文件",
      link2: "博客",
      link3: "条款和条件",
      link4: "隐私政策",
    },
    landing: {
      hero: {
        btn1: "发射台",
        title: "尽早获得最佳项目",
        titleGr: "有序生态系统",
        sub: "经过验证的项目将推动未来",
        subGr: "比特币序数生态系统",
        btn2: "提交项目",
        btn3: "参与预售",
        value1: "资助项目",
        value2: "项目 MKT 上限",
        value3: "独特的参与者",
        cardText: {
          imgText: "特色项目",
          date: "开始",
          desc: "专为比特币序数生态系统构建的终极发射台。",
          btn1: "代币销售",
          btn2: "在这里买",
          price: "每个令牌的价格",
          allocation: "分配",
        },
      },
      funds: {
        title: "筹集的资金用于在",
        titleGr: "序数",
        titleEnd: "生态系统",
        box1: "募集总额",
        box2: "资助代币",
        box3: "总市值",
        box4: "参与者总数",
      },
      how: {
        title: "我如何购买 Ordinal Pad $OPAD 代币？",
        btn: "购买 $OPAD",
      },
      upcoming: {
        title: "即将进行的项目",
        sub: "我们引入了 Ordinal 生态系统中一些经过最严格审查和最成功的项目",
        days: "天",
        hours: "小时",
        min: "协议",
        sec: "秒",
        date: "开始",
        price: "每个令牌的价格",
        allocation: "分配",
        note: "提供一个平台来支持最具创新性的有序项目",
        btnCard: "代币销售",
        btn1: "查看所有内容",
      },
      brand: {
        btn1: "发射台",
        title: "品牌代言人",
        btn2: "查看所有内容",
        followers: "扇子",
      },
      launched: {
        title: "开始",
        titleGr: "项目",
        raised: "募集总额",
        participants: "参与者",
        ended: "完全的",
      },
      sale: {
        title: "不想错过促销活动？",
        btn: "加入我们的社区",
      },
    },
    projectDetails: {
      hero: {
        title: "项目详情",
        desc: "专为 Ordinal 生态系统设计的终极启动板",
        owner: "所有者",
        chain: "区块链",
        address: "合约地址",
        id: "代币编号",
        standard: "代币标准",
        fees: "合同费",
        time: "开始时间",
        btn1: "图表",
        btn2: "立即购买",
      },
      desc: {
        tab1: "描述",
        tab2: "代币销售",
        titleGr: "原装垫",
        title: "是 Ordinal 生态系统的完美启动平台，原因如下：",
        para1:
          "- 首先，它是一个用户友好且安全的平台，允许用户在项目启动之前轻松参与 Ordinal 最有前途的项目。由于我们平台的简单直观设计，即使是那些不熟悉加密货币和 DeFi 的人也可以轻松浏览平台并参与项目，而无需任何技术知识。",
        para2:
          "- 其次，Ordinal Pad 集成了各种功能，使用户在等待新项目开始时更容易抵押他们的代币以获得丰厚的收益。此外，我们正在建立一个强大的用户和开发人员社区，他们不断致力于改进平台、添加新功能和优化现有功能。",
        para3:
          "总的来说，Ordinal Pad 的可访问性、用户友好的界面和强大的功能使其成为 Ordinal 生态系统的完美启动板。",
        btn1: "白皮书",
        tags: "关键词",
        social: "社会的",
      },
    },
  },
};
